#!/bin/sh

LF='
'

VN=$(git describe --match "v[0-9]*" --abbrev=4 HEAD 2>/dev/null)
case "$VN" in
    *$LF*) (exit 1) ;;
v[0-9]*)
        git update-index -q --refresh
        test -z "$(git diff-index --name-only HEAD --)" ||
        VN="$VN-dirty" ;;
esac
VN=$(echo "$VN" | sed -e 's/-/./g');
VN=$(expr "$VN" : v*'\(.*\)')

echo "$VN"
